// <auto-generated />
namespace DevLunch.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class add_votetype : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_votetype));
        
        string IMigrationMetadata.Id
        {
            get { return "201605181542331_add_votetype"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
